on:
  push:
  pull_request:

jobs:
  rust:
    name: Lint Rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Cargo test
        run: cargo test --workspace

  generate-winmd:
    name: Generate winmd
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Clean
        run: Remove-Item -Recurse -Force .windows/winmd/
      - name: Configure environment
        shell: pwsh
        run: |
          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64" >> $env:GITHUB_PATH
          ((Resolve-Path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\*\bin\Hostx64\x64")
            | Sort-Object -Descending | Select -First 1).ToString() >> $env:GITHUB_PATH
      - name: Generate
        run: dotnet build .metadata
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: metadata
          path: .windows/winmd

  generate-rust:
    name: Generate Rust crate
    runs-on: ubuntu-latest
    needs: generate-winmd
    steps:
      - uses: actions/checkout@v3
      - name: Clean
        run: rm -rf .windows/winmd/ src/Amd/
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: metadata
          path: .windows/winmd
      - name: Install riddle
        run: cargo install --git https://github.com/microsoft/windows-rs --rev f18811c riddle
      - name: Generate
        run: riddle --etc bindings.txt
      - name: Upload crate source
        uses: actions/upload-artifact@v3
        with:
          name: crate-source
          path: src/
      - name: Diff generated Rust code
        run: test -z "$(git status --porcelain -- '!.windows')" || (echo "::error::Generated files are different, please regenerate with riddle --etc bindings.txt!"; git diff; false)
